// js/data.js — CineMatch dataset

const QUIZ_QUESTIONS = [
  {
    id: "mood",
    question: "What kind of mood are you in?",
    emoji: "🎭",
    type: "single",
    options: [
      { label: "Thrilled & on-edge", value: "thriller", icon: "⚡" },
      { label: "Laughing out loud", value: "comedy", icon: "😂" },
      { label: "Deeply moved", value: "drama", icon: "💔" },
      { label: "Mind blown", value: "scifi", icon: "🚀" },
      { label: "Scared & screaming", value: "horror", icon: "👻" },
      { label: "Swept into adventure", value: "adventure", icon: "🗺️" },
    ],
  },
  {
    id: "format",
    question: "Movie or series?",
    emoji: "📺",
    type: "single",
    options: [
      { label: "Movie — done in 2 hours", value: "movie", icon: "🎬" },
      { label: "Series — I want more episodes", value: "series", icon: "📺" },
      { label: "Either works for me", value: "both", icon: "🤷" },
    ],
  },
  {
    id: "era",
    question: "Any era preference?",
    emoji: "📅",
    type: "single",
    options: [
      { label: "Classic (pre-2000)", value: "classic", icon: "🎞️" },
      { label: "2000s–2015", value: "mid", icon: "📼" },
      { label: "Recent (2016–now)", value: "recent", icon: "✨" },
      { label: "No preference", value: "any", icon: "🌀" },
    ],
  },
  {
    id: "vibe",
    question: "Pick your vibe:",
    emoji: "✨",
    type: "single",
    options: [
      { label: "Dark & gritty", value: "dark", icon: "🌑" },
      { label: "Light & fun", value: "light", icon: "☀️" },
      { label: "Thought-provoking", value: "intellectual", icon: "🧠" },
      { label: "Feel-good & warm", value: "feelgood", icon: "🌈" },
      { label: "Epic & grand", value: "epic", icon: "🏔️" },
    ],
  },
  {
    id: "company",
    question: "Who are you watching with?",
    emoji: "👥",
    type: "single",
    options: [
      { label: "Solo — just me", value: "solo", icon: "🙋" },
      { label: "Partner / date night", value: "date", icon: "💑" },
      { label: "Friends group", value: "friends", icon: "🎉" },
      { label: "Family with kids", value: "family", icon: "👨‍👩‍👧" },
    ],
  },
  {
    id: "language",
    question: "Language preference?",
    emoji: "🌍",
    type: "single",
    options: [
      { label: "English only", value: "english", icon: "🇬🇧" },
      { label: "Fine with subtitles", value: "subtitles", icon: "💬" },
      { label: "No preference", value: "any_lang", icon: "🌐" },
    ],
  },
];

const CATALOG = [
  // ── THRILLERS ──────────────────────────────────────────
  {
    id: 1, title: "Parasite", year: 2019, type: "movie",
    genres: ["thriller", "drama"], vibe: ["dark", "intellectual"],
    language: "korean", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.5, poster: "🪱",
    posterColor: "#1a0a2e",
    desc: "A poor family schemes to become employed by a wealthy household in this razor-sharp social satire.",
    tags: ["Oscar winner", "Bong Joon-ho", "Class warfare"],
  },
  {
    id: 2, title: "Gone Girl", year: 2014, type: "movie",
    genres: ["thriller", "drama"], vibe: ["dark", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.1, poster: "🔪",
    posterColor: "#0d1b2a",
    desc: "On the morning of his fifth wedding anniversary, Nick Dunne reports his wife, Amy, is missing.",
    tags: ["David Fincher", "Psychological", "Twist ending"],
  },
  {
    id: 3, title: "Inception", year: 2010, type: "movie",
    genres: ["thriller", "scifi"], vibe: ["intellectual", "epic"],
    language: "english", era: "mid",
    company: ["solo", "date", "friends"],
    rating: 8.8, poster: "🌀",
    posterColor: "#0a1628",
    desc: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.",
    tags: ["Christopher Nolan", "Mind-bending", "Hans Zimmer"],
  },
  {
    id: 4, title: "Mindhunter", year: 2017, type: "series",
    genres: ["thriller", "drama"], vibe: ["dark", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.6, poster: "🔦",
    posterColor: "#111111",
    desc: "FBI agents Holden Ford and Bill Tench interview serial killers to develop criminal profiling techniques.",
    tags: ["David Fincher", "True crime", "Serial killers"],
  },
  {
    id: 5, title: "Oldboy", year: 2003, type: "movie",
    genres: ["thriller", "drama"], vibe: ["dark"],
    language: "korean", era: "classic",
    company: ["solo"],
    rating: 8.4, poster: "🪚",
    posterColor: "#1c0a0a",
    desc: "After being inexplicably imprisoned for 15 years, a man is suddenly released and seeks revenge.",
    tags: ["Park Chan-wook", "Shocking", "Cult classic"],
  },
  // ── SCI-FI ──────────────────────────────────────────────
  {
    id: 6, title: "Interstellar", year: 2014, type: "movie",
    genres: ["scifi", "adventure"], vibe: ["epic", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.7, poster: "🪐",
    posterColor: "#080820",
    desc: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    tags: ["Christopher Nolan", "Space", "Hans Zimmer"],
  },
  {
    id: 7, title: "Arrival", year: 2016, type: "movie",
    genres: ["scifi", "drama"], vibe: ["intellectual", "dark"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.0, poster: "🛸",
    posterColor: "#0e1a14",
    desc: "When twelve mysterious spacecraft appear around the world, a linguist works to communicate with the aliens.",
    tags: ["Denis Villeneuve", "Linguistics", "Emotional"],
  },
  {
    id: 8, title: "Black Mirror", year: 2011, type: "series",
    genres: ["scifi", "thriller"], vibe: ["dark", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.8, poster: "📱",
    posterColor: "#0d0d0d",
    desc: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations collide with its darkest instincts.",
    tags: ["Anthology", "Technology", "Charlie Brooker"],
  },
  {
    id: 9, title: "Dune: Part Two", year: 2024, type: "movie",
    genres: ["scifi", "adventure"], vibe: ["epic", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.6, poster: "🏜️",
    posterColor: "#1a1000",
    desc: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    tags: ["Denis Villeneuve", "Visually stunning", "Epic scale"],
  },
  {
    id: 10, title: "Severance", year: 2022, type: "series",
    genres: ["scifi", "thriller"], vibe: ["dark", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.7, poster: "🗂️",
    posterColor: "#101520",
    desc: "A thriller series about workers whose memories are surgically divided between their work and personal lives.",
    tags: ["Apple TV+", "Office horror", "Mind-bending"],
  },
  // ── COMEDY ──────────────────────────────────────────────
  {
    id: 11, title: "The Grand Budapest Hotel", year: 2014, type: "movie",
    genres: ["comedy", "adventure"], vibe: ["light", "epic"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.1, poster: "🏨",
    posterColor: "#3d0e1e",
    desc: "A writer encounters the owner of an aging European hotel between the wars and learns about his early life.",
    tags: ["Wes Anderson", "Quirky", "Colour palette"],
  },
  {
    id: 12, title: "What We Do in the Shadows", year: 2019, type: "series",
    genres: ["comedy", "horror"], vibe: ["light", "dark"],
    language: "english", era: "recent",
    company: ["solo", "friends"],
    rating: 8.6, poster: "🧛",
    posterColor: "#1a0028",
    desc: "A documentary crew follows three vampire roommates navigating daily life in modern Staten Island.",
    tags: ["Mockumentary", "Jemaine Clement", "Absurdist"],
  },
  {
    id: 13, title: "The Office (US)", year: 2005, type: "series",
    genres: ["comedy"], vibe: ["light", "feelgood"],
    language: "english", era: "mid",
    company: ["solo", "friends", "date"],
    rating: 9.0, poster: "📋",
    posterColor: "#1c2a1c",
    desc: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes and inappropriate jokes.",
    tags: ["Comfort watch", "Steve Carell", "Mockumentary"],
  },
  {
    id: 14, title: "Knives Out", year: 2019, type: "movie",
    genres: ["comedy", "thriller"], vibe: ["light", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "friends", "date", "family"],
    rating: 8.0, poster: "🔍",
    posterColor: "#1a0f00",
    desc: "A detective investigates the death of a patriarch of an eccentric, combative family.",
    tags: ["Whodunit", "Daniel Craig", "Ensemble cast"],
  },
  {
    id: 15, title: "Abbott Elementary", year: 2021, type: "series",
    genres: ["comedy"], vibe: ["light", "feelgood"],
    language: "english", era: "recent",
    company: ["solo", "friends", "family"],
    rating: 8.2, poster: "🏫",
    posterColor: "#0d2200",
    desc: "A group of dedicated teachers — and an oblivious principal — work in an underfunded Philadelphia public school.",
    tags: ["Heartwarming", "Mockumentary", "Emmy winner"],
  },
  // ── DRAMA ──────────────────────────────────────────────
  {
    id: 16, title: "Breaking Bad", year: 2008, type: "series",
    genres: ["drama", "thriller"], vibe: ["dark"],
    language: "english", era: "mid",
    company: ["solo", "date"],
    rating: 9.5, poster: "⚗️",
    posterColor: "#1a1200",
    desc: "A chemistry teacher diagnosed with inoperable cancer turns to manufacturing drugs to secure his family's future.",
    tags: ["Vince Gilligan", "Greatest TV", "Character study"],
  },
  {
    id: 17, title: "Succession", year: 2018, type: "series",
    genres: ["drama", "comedy"], vibe: ["dark", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.9, poster: "👔",
    posterColor: "#0a0a14",
    desc: "The Roy family controls one of the biggest media and entertainment conglomerates in the world but the future of the business is uncertain.",
    tags: ["Power dynamics", "Dialogue", "Emmy winner"],
  },
  {
    id: 18, title: "The Shawshank Redemption", year: 1994, type: "movie",
    genres: ["drama"], vibe: ["feelgood", "dark"],
    language: "english", era: "classic",
    company: ["solo", "date", "friends"],
    rating: 9.3, poster: "🏛️",
    posterColor: "#0d1a0d",
    desc: "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
    tags: ["IMDB #1", "Stephen King", "Hope"],
  },
  {
    id: 19, title: "Normal People", year: 2020, type: "series",
    genres: ["drama"], vibe: ["feelgood", "dark"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.0, poster: "💞",
    posterColor: "#1c0a10",
    desc: "Follows the complex relationship of Connell and Marianne through their college years in Ireland.",
    tags: ["Sally Rooney", "Romance", "Emotional"],
  },
  {
    id: 20, title: "Shogun (2024)", year: 2024, type: "series",
    genres: ["drama", "adventure"], vibe: ["epic", "dark"],
    language: "subtitles", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.9, poster: "⚔️",
    posterColor: "#1a0a00",
    desc: "A shipwrecked English navigator becomes a key player in feudal Japanese politics.",
    tags: ["Emmy winner", "Epic", "Historical"],
  },
  // ── HORROR ──────────────────────────────────────────────
  {
    id: 21, title: "Hereditary", year: 2018, type: "movie",
    genres: ["horror", "thriller"], vibe: ["dark"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 7.8, poster: "🏚️",
    posterColor: "#120000",
    desc: "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.",
    tags: ["Ari Aster", "A24", "Slow burn"],
  },
  {
    id: 22, title: "The Haunting of Hill House", year: 2018, type: "series",
    genres: ["horror", "drama"], vibe: ["dark"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.6, poster: "👁️",
    posterColor: "#0a0014",
    desc: "Flashing between past and present, a fractured family confronts haunting memories of their old home.",
    tags: ["Mike Flanagan", "Family drama", "Atmosphere"],
  },
  {
    id: 23, title: "Get Out", year: 2017, type: "movie",
    genres: ["horror", "thriller"], vibe: ["dark", "intellectual"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 7.7, poster: "🪑",
    posterColor: "#0d0d0d",
    desc: "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness mounts.",
    tags: ["Jordan Peele", "Social commentary", "Oscar winner"],
  },
  // ── ADVENTURE / ACTION ─────────────────────────────────
  {
    id: 24, title: "Mad Max: Fury Road", year: 2015, type: "movie",
    genres: ["adventure", "thriller"], vibe: ["epic", "dark"],
    language: "english", era: "recent",
    company: ["solo", "friends"],
    rating: 8.1, poster: "🔥",
    posterColor: "#1a0800",
    desc: "In a post-apocalyptic wasteland, Max teams up with Furiosa to flee from a cult leader and his army.",
    tags: ["George Miller", "Practical effects", "Relentless"],
  },
  {
    id: 25, title: "Everything Everywhere All at Once", year: 2022, type: "movie",
    genres: ["adventure", "comedy", "scifi"], vibe: ["intellectual", "feelgood", "light"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.0, poster: "🥢",
    posterColor: "#0d001a",
    desc: "A middle-aged Chinese-American laundromat owner must connect with parallel universe versions of herself to prevent a powerful villain from destroying the multiverse.",
    tags: ["A24", "Oscar winner", "Multiverse"],
  },
  {
    id: 26, title: "Andor", year: 2022, type: "series",
    genres: ["adventure", "scifi", "drama"], vibe: ["dark", "epic"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends"],
    rating: 8.5, poster: "🌌",
    posterColor: "#050a14",
    desc: "The story of the formative years of Rebel spy Cassian Andor during the Dark Times of the Empire.",
    tags: ["Star Wars", "Grounded", "Political thriller"],
  },
  // ── FEEL-GOOD / FAMILY ─────────────────────────────────
  {
    id: 27, title: "Ted Lasso", year: 2020, type: "series",
    genres: ["comedy", "drama"], vibe: ["feelgood", "light"],
    language: "english", era: "recent",
    company: ["solo", "date", "friends", "family"],
    rating: 8.8, poster: "⚽",
    posterColor: "#001a0a",
    desc: "An American college football coach is hired to manage an English soccer team despite having no experience with the sport.",
    tags: ["Wholesome", "AppleTV+", "Feel-good"],
  },
  {
    id: 28, title: "Klaus", year: 2019, type: "movie",
    genres: ["adventure", "comedy"], vibe: ["feelgood", "light"],
    language: "english", era: "recent",
    company: ["solo", "family", "friends"],
    rating: 8.2, poster: "🎅",
    posterColor: "#00101a",
    desc: "A selfish postal worker and a reclusive toymaker form an unlikely friendship in this reimagined Santa Claus origin story.",
    tags: ["Netflix animated", "Heartwarming", "Beautiful art"],
  },
  {
    id: 29, title: "The Bear", year: 2022, type: "series",
    genres: ["drama", "comedy"], vibe: ["dark", "intellectual", "feelgood"],
    language: "english", era: "recent",
    company: ["solo", "date"],
    rating: 8.8, poster: "🐻",
    posterColor: "#120800",
    desc: "A young fine-dining chef returns to Chicago to run his family's sandwich shop after a death in the family.",
    tags: ["Emmy winner", "Intense", "Food"],
  },
  {
    id: 30, title: "Hana-Bi", year: 1997, type: "movie",
    genres: ["drama", "thriller"], vibe: ["dark", "intellectual"],
    language: "japanese", era: "classic",
    company: ["solo"],
    rating: 8.0, poster: "🌸",
    posterColor: "#0a0a1a",
    desc: "A detective caring for his terminally ill wife turns to violent crime to cover his debts and give her a final journey.",
    tags: ["Kitano Takeshi", "Art house", "Venice winner"],
  },
];

// Titles shown during the rating/calibration phase
const RATING_POOL = [
  { id: 101, title: "The Dark Knight", emoji: "🦇", year: 2008 },
  { id: 102, title: "Pulp Fiction", emoji: "💉", year: 1994 },
  { id: 103, title: "Avengers: Endgame", emoji: "🛡️", year: 2019 },
  { id: 104, title: "Stranger Things", emoji: "🔦", year: 2016 },
  { id: 105, title: "Game of Thrones", emoji: "🐉", year: 2011 },
  { id: 106, title: "The Matrix", emoji: "💊", year: 1999 },
  { id: 107, title: "Squid Game", emoji: "🟩", year: 2021 },
  { id: 108, title: "La La Land", emoji: "🎷", year: 2016 },
  { id: 109, title: "The Silence of the Lambs", emoji: "🦋", year: 1991 },
  { id: 110, title: "Friends", emoji: "☕", year: 1994 },
  { id: 111, title: "Titanic", emoji: "🚢", year: 1997 },
  { id: 112, title: "The Lord of the Rings", emoji: "💍", year: 2001 },
  { id: 113, title: "Schindler's List", emoji: "📋", year: 1993 },
  { id: 114, title: "Forrest Gump", emoji: "🏃", year: 1994 },
  { id: 115, title: "The Sopranos", emoji: "🎻", year: 1999 },
];

// Rating → genre affinity map (what ratings of known titles tell us)
const TITLE_GENRE_MAP = {
  101: ["thriller", "dark", "epic"],
  102: ["thriller", "dark", "intellectual"],
  103: ["adventure", "epic", "feelgood"],
  104: ["scifi", "thriller", "dark"],
  105: ["drama", "adventure", "dark", "epic"],
  106: ["scifi", "thriller", "intellectual"],
  107: ["thriller", "dark"],
  108: ["drama", "comedy", "feelgood", "light"],
  109: ["thriller", "dark", "intellectual"],
  110: ["comedy", "feelgood", "light"],
  111: ["drama", "feelgood"],
  112: ["adventure", "epic", "feelgood"],
  113: ["drama", "dark", "intellectual"],
  114: ["drama", "feelgood", "light"],
  115: ["drama", "thriller", "dark"],
};
